### ISSUE TITLE
Adding a dropdown component that is similar to dcc.Dropdown

### ISSUE THREAD

**Issue by mbkupfer** [facultyai/dash-bootstrap-components#122]
Dash's dcc.Dropdown doesn't style easily, at least from my experience. 
Is there a way to add a dbc dropdown component that can change the size and appearance in the same way that [input](https://dash-bootstrap-components.opensource.asidatascience.com/l/components/input) does for dcc.Input?

**Comment by tcbegley** [comment]
Hi @mbkupfer

Good suggestion, I think this is worth adding.

I also want to do the same properly for the DatePicker components. Currently the DatePickers match default Bootstrap styles, but don’t work very well with Bootswatch because the styling is hard coded.

**Comment by tcbegley** [comment]
Hey @mbkupfer 

It's been a while since you opened this issue, sorry about that. We're moving away from including our own `Dropdown` component, primarily because it seems wasteful to duplicate functionality that's present in *dash-core-components*. Instead we're moving towards providing Bootstrap stylesheets that add styling for *dash-core-components* etc. I've started working on that [here](https://github.com/tcbegley/dash-bootstrap-css). It's pretty early stages at the moment, but since you enquired about this specifically I thought you might be interested. I'm also very interested in feedback if you have any.

Long term, if this approach seems good, we may serve these stylesheets over a CDN, and make them available through `dbc.themes`. For now though, just download from the repo and link them locally.

**Comment by mbkupfer** [comment]
@tcbegley thanks for getting back to me on this and no worries. 

I tried it out and it looks nice but I think it adds a lot of css layers that makes styling a pain. I also noticed that it's important how the css files are names when placed in the assets folder of the dash app since dash reads them in order. For instance, if the bootstrap stylesheet was last, then my whole app had a new style and not just the div that I designated. My technique here has been to just give the files a 2 digit prefix: 
| assets
| -- 01_first_style_sheet.css
| -- 02_second_style_sheet.css

Might help to point that out in the documentation of the project.

**Comment by jmsblah** [comment]
> @tcbegley thanks for getting back to me on this and no worries.
> 
> I tried it out and it looks nice but I think it adds a lot of css layers that makes styling a pain. I also noticed that it's important how the css files are names when placed in the assets folder of the dash app since dash reads them in order. For instance, if the bootstrap stylesheet was last, then my whole app had a new style and not just the div that I designated. My technique here has been to just give the files a 2 digit prefix:
> | assets
> | -- 01_first_style_sheet.css
> | -- 02_second_style_sheet.css
> 
> Might help to point that out in the documentation of the project.

In fact, prefixing the filenames is something recommended in the [Dash external resource documentation](https://dash.plot.ly/external-resources).

> 2 - Dash will include the files in alphanumerical order by filename. So, we recommend prefixing your filenames with numbers if you need to ensure their order (e.g. 10_typography.css, 20_header.css)

**Comment by mbkupfer** [comment]
>In fact, prefixing the filenames is something recommended in the Dash external resource documentation.

Ah, yes, that is wear I remember seeing this. 

Either way, I thought this was important given your isolation from dash core component styling approach via the `className="dash-bootstrap"` convention.

**Comment by tcbegley** [comment]
>  I think it adds a lot of css layers that makes styling a pain.

I definitely hear you on this, but in some sense that is out of our hands. The `dcc.Dropdown` is styled using all of those classes, and it doesn't allow you to modify any of them by setting props. As a result the two options are 

1) Override the existing CSS classes, which is certainly messy, though the idea here is that we figure out how to do it, so that you don't have to. 
2) Build our own `Dropdown` component and set the styles there. The main problem here is that this means we add dependencies to *dash-bootstrap-components* causing our bundle to get bloated, and we're duplicating functionality which we would have to keep in sync with *dash-core-components*. It's also not clear how we would add inline styles that would be compatible with all the different Bootstrap / Bootswatch themes.

> if the bootstrap stylesheet was last, then my whole app had a new style and not just the div that I designated

The stylesheets in that repo are Bootstrap + styles for *dash-core-components*. It's only the latter that is restricted to being applied inside the `.dash-bootstrap` class, it also includes all of Bootstrap CSS which will affect styles outside of the `.dash-bootstrap` class. I will clarify that in the readme.

Thanks for taking a look and your comments! It's helpful to understand better how to make this sort of thing useful to people.

**Comment by tcbegley** [comment]
Closing this in favour of the approach of #147
