### ISSUE TITLE
Add font awesome icon

### ISSUE THREAD

**Issue by happyshows** [facultyai/dash-bootstrap-components#133]
Hi,

Is it possible to add icon support in next release? Similar to what shiny button supports.

**Comment by pbugnion** [comment]
Thanks for raising this!

Fontawesome support would be great. I'm not sure whether this belongs directly in dash-bootstrap-components or in a separate layer.

For reference, the RShiny interface looks like:

```R
navbarPage("App Title",
  tabPanel("Plot", icon = icon("bar-chart-o")),
  tabPanel("Summary", icon = icon("list-alt")),
  tabPanel("Table", icon = icon("table"))
)
```

More details in the [RShiny docs](https://shiny.rstudio.com/reference/shiny/1.0.1/icon.html).

**Comment by tcbegley** [comment]
Thanks for suggesting this. I agree I'm not sure whether this belongs in *dash-bootstrap-components*.

The Shiny interface I think is a little restrictive, for example, something like

```r
submitButton("Update View", icon = icon("refresh"))
```

generates the following HTML structure

```html
<div>
  <button type="submit" class="btn btn-primary">
    <i class="fa fa-refresh"></i>
    Update View
  </button>
</div>
```

but perhaps a user might like to position the icon after the text, which would be difficult with this interface.

Instead I think icons as children rather than icons as props is more flexible. In Dash a hypothetical `Icon` component might look like

```python
html.Div([
    dbc.Button([Icon("refresh"), "Icon before"]),
    dbc.Button(["Icon after", Icon("refresh")]),
])
```

Such a component may make most sense in its own library, so that people can easily use Font Awesome without Bootstrap, or Bootstrap without Font Awesome if they wish. That would be a nice little addition to the Dash ecosystem though, much nicer than manually adding `html.I(className="fa fa-refresh")` or similar all the time.

**Comment by happyshows** [comment]
that's why I currently use, thanks for the detailed explanation.

**Comment by pbugnion** [comment]
It sounds like a *dash-font-awesome* library that implements `Icon("refresh")` would be a good addition to the ecosystem.

For anyone wanting to implement this -- I suggest looking at how dash-bootstrap-components manages loading CSS (through the themes package -- see, e.g. 'Getting started' in the [docs](https://dash-bootstrap-components.opensource.faculty.ai/)). Converging on a standard for linking external CSS would be useful.

**Comment by happyshows** [comment]
@pbugnion  could you post the link for dash-font-awesome? I can't find it...

**Comment by pbugnion** [comment]
Sorry -- my message was a bit unclear. I think someone should write that library. It doesn't exist yet.
