### ISSUE TITLE
Multi-Value Dropdown

### ISSUE THREAD

**Issue by bearsh** [facultyai/dash-bootstrap-components#174]
Hi

It would be nice to have multi value support in the dropdown like dash has.

**Comment by tcbegley** [comment]
Hi @bearsh 

Thanks for raising this. Could you elaborate a bit on what you would expect this to look like / how you would like to use it?

**Comment by bearsh** [comment]
At the moment I use it to select channels from a data source to show in a plot. I couldn't find anything better / more compact.
Regarding the look, the selection should work like the one provided by dash, the look like the dropdown provided by this project.

**Comment by tcbegley** [comment]
I think if you want the same functionality as the `dcc.Dropdown`, it would be better to use that and try to modify the CSS / styles to get the right look for your app. Our `DropdownMenu` is really meant to be used more as a way of gathering and organising links to navigate a multi-page app. It would be pretty hard for us to support e.g. multiple selections, or dynamically generated / very large lists of options without quite substantially changing the component.

**Comment by bearsh** [comment]
Fair enough! Thank you anyway, gonna close it...

**Comment by tcbegley** [comment]
No problem, sorry I couldn't be more help.

I responded to someone yesterday on the plotly forum who had a similar question. Maybe [my answer there](https://community.plot.ly/t/dash-bootstrap-components-dropdownmenu-value/22011/6) on styling the dash-core-components Dropdown is helpful.

**Comment by acoque** [comment]
Hello there !

First, thanks for the nice work you've done. It's realy easy to design a nice-looking dashboard using this package.

I'm in the exact same situation than bearch, except than I'm using dbc.Select components instead of a dbc.Dropdown (dbc.Select didn't exist when this issue was first open by bearsh) and I was then wondering if you were planning to implement multivalue support for this component (for instance in the same way than dcc.Dropdown works, with a *multi=True* flag).

I could use dcc.Dropdown as it is but it doesn't work well inside of an InputGroup with an InputGroupAppend (as you can see on the following picture).
![select](https://user-images.githubusercontent.com/35691279/81147904-88f92480-8f7b-11ea-84ed-3684c0a06842.png)

Thanks ;)

(Otherwise, maybe I should try to modify the style of dcc.Dropdown 🤔)
