### ISSUE TITLE
0.5.0 update for Anaconda

### ISSUE THREAD

**Issue by algerjiang** [facultyai/dash-bootstrap-components#188]
I'm working with Anaconda,  after searched in anaconda site,  it shows that the last update is  0.3.1:
https://anaconda.org/search?q=dash-bootstrap-components,
It's a cumbersome for people to transfer pypi pkgs to conda pkgs,
I think that'll be really appreciated if you people update dbc component in conda pkg regularly or after some major changed has been made.

thanks :)

**Comment by tcbegley** [comment]
Hi @algerjiang 

That wasn't actually created by us, I think someone made it for their own personal use?

In any case, I agree that it would be good if we started publishing to conda. I'll see if we can get it added to our release pipeline.

Thanks for raising.

**Comment by algerjiang** [comment]
> Hi @algerjiang
> 
> That wasn't actually created by us, I think someone made it for their own personal use?
> 
> In any case, I agree that it would be good if we released dbc as a conda package. I'll see if we can get it added to our release pipeline.
> 
> Thanks for raising.

Thanks for your quick reply!

Yes, I checked the author name, it's obviously updated by some other good people. 
well, it shows that there are actual many needs to get the dbc via anaconda channel.. :)

Looking forward to get official adc component in anaconda channel.

BTW: The abc component is really cool. In past weeks I've struggled to implement some web layout features in my dash apps, until I found your dbc component...

**Comment by tcbegley** [comment]
Just a bit of an update on this. In order to build packages for anaconda, it's necessary that all dependencies are available through anaconda too. Unfortunately it seems that while Plotly has uploaded Dash to anaconda in the past, it's not being kept up to date (last version uploaded was Dash 0.39.0, we're now on 0.43.0, with some pretty major changes in between).

Until Dash is being kept up to date on anaconda, I don't think we can reliably put _dash-bootstrap-components_ up there. It may be worth seeking some clarification from the Dash team why the last few versions weren't uploaded. There's [this open issue](https://github.com/plotly/dash/issues/79) that looks relevant.

**Comment by tcbegley** [comment]
Ignore my previous comment, looks like Dash is now hosted on the conda-forge channel which is why they stopped updating the version on the plotly channel. Looking in to this at the moment. Sorry it's taken a while to get around to it.

**Comment by holtgrewe** [comment]
@tcbegley Hm, maybe ask on gittr in the conda-forge how that works :)

**Comment by tcbegley** [comment]
Well as far as I understand it’s all very automated, so If there is nothing to do then great, but wanted to offer our support in case I am incorrect about that

In any case, thanks for adding the package to conda-forge in the first place :)

**Comment by holtgrewe** [comment]
@tcbegley Maybe the way to go is to add yourself to the maintainer list via a PR in the corresponding feedstock repository. Or rather just replace me :)

Anyway, thanks for dbc, excellent work!

**Comment by tcbegley** [comment]
I just merged #218 which adds installation instructions for conda to the readme and the docs, so I'll close this now.
