### ISSUE TITLE
Graph under inactive dbc.Tab occupies half the container size

### ISSUE THREAD

**Issue by eliasdabbas** [facultyai/dash-bootstrap-components#211]
Hello, 

I have two tabs with a `dcc.Graph` in each. 
The active tab shows the graph properly, but the inactive tab shows it in half-size. It needs resetting of axes. There is no way the end user is going to figure this out, and the second graph is not easy to use therefore. 

Here is a minimal example showing the first graph occupying the full container width, while the second only half of it: 

```
import dash
import dash_html_components as html
import dash_core_components as dcc
import dash_bootstrap_components as dbc


app = dash.Dash(__name__, external_stylesheets=[dbc.themes.COSMO])

app.layout = html.Div([
    dbc.Tabs([
        dbc.Tab([
            dcc.Graph(id='Graph 1')
        ], label='Tab 1'),
        dbc.Tab([
            dcc.Graph(id='Graph 2')
        ], label='Tab 2'),
    ])
])


if __name__ == '__main__':
    app.run_server(debug=True)

```

Any idea how to get both to occupy the full container? Am I doing anything wrong? 

Packages: 

```
dash==0.43.0
dash-bootstrap-components==0.6.0
dash-core-components==0.48.0
dash-html-components==0.16.0
dash-renderer==0.24.0
```

Thanks!

**Comment by tcbegley** [comment]
Hey @eliasdabbas 

The reason this happens is because `dbc.Tabs` uses `<div>` elements under the hood with `display` set to `none` to hide inactive tabs. While a Plotly graph is inside a hidden `<div>` it is unable to determine the width of the parent container, and so it defaults to some fixed width. You can read more about that [here](https://community.plot.ly/t/plotly-resize-bug-using-html-details-hidden-div-and-width-100/11201), and you'll observe the same kind of problem if you use something like `html.Details` instead of `dbc.Tabs`.

The way to fix it is to dynamically render the tab content using the `active-tab` property of `dbc.Tabs`. You can check out [this example](https://github.com/facultyai/dash-bootstrap-components/blob/master/examples/advanced-component-usage/graphs_in_tabs.py) or [this forum post](https://community.plot.ly/t/graph-in-tabs-not-extending-to-all-screen/21806/2) for some guidance.

**Comment by eliasdabbas** [comment]
Got it. Thanks for sharing the links! 
I'll see how best to implement in my case. 

I also found out that when going to the inactive tab and double clicking the chart area (or clicking the 'reset axes' button) the chart takes the full container width and behaves as expected. 

The solution would be simple and straightforward if there was a way to initialize the `dcc.Graph` with the 'reset axes' button clicked (or induce a click somehow, through the callback that produces it). Not sure if that's possible.

**Comment by tcbegley** [comment]
> The solution would be simple and straightforward if there was a way to initialize the `dcc.Graph` with the 'reset axes' button clicked

The problem is that the `Graph` is initialized inside a hidden container so at initialization time resetting the axes won't help. You need to trigger a redraw when the tab is changed, and the easiest way is to render tab content dynamically.

I think the underlying problem is hard to fix, see [here](https://github.com/plotly/plotly.js/issues/2769) for example.

**Comment by eliasdabbas** [comment]
I see. Thanks. Setting the width by pixels might also be a good idea as mentioned in the link you shared. Actually, it works for my specific case. 

Good to know that this is a known issue, and keep in mind in similar cases.

Thanks again!
