### ISSUE TITLE
Files not found during install

### ISSUE THREAD

**Issue by arthurdelaitre** [facultyai/dash-bootstrap-components#232]
Hello,
I've tried to build the package after clonning it to my computer, but the builds fails to find some dependancies. Here are the prints :
```
running build
running build_py
creating build
creating build\lib
creating build\lib\dash_bootstrap_components
copying dash_bootstrap_components\table.py -> build\lib\dash_bootstrap_components
copying dash_bootstrap_components\themes.py -> build\lib\dash_bootstrap_components
copying dash_bootstrap_components\_version.py -> build\lib\dash_bootstrap_components
copying dash_bootstrap_components\__init__.py -> build\lib\dash_bootstrap_components
running egg_info
creating dash_bootstrap_components.egg-info
writing dash_bootstrap_components.egg-info\PKG-INFO
writing dependency_links to dash_bootstrap_components.egg-info\dependency_links.txt
writing requirements to dash_bootstrap_components.egg-info\requires.txt
writing top-level names to dash_bootstrap_components.egg-info\top_level.txt
writing manifest file 'dash_bootstrap_components.egg-info\SOURCES.txt'
reading manifest file 'dash_bootstrap_components.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'dash_bootstrap_components\_components\dash_bootstrap_components.min.js'
warning: no files found matching 'dash_bootstrap_components\_components\metadata.json'
writing manifest file 'dash_bootstrap_components.egg-info\SOURCES.txt'
```

It seems dash_bootstrap_components.min.js and metadata.json can't be located. When I install the package using conda, I get the same problem after using pyinstaller to make an exe (those files can't be located and result in the exe to crash).

Does anyone know how to resolve this ?

Python : 3.6.8
Windows 10
Pyinstaller 3.4
Using dash-bootstrap-components 0.6.3 when installing with conda

**Comment by tcbegley** [comment]
Hi @arthurdelaitre 

There are a number of Python and javascript files that are generated from the javascript source in this repo that we don't keep under version control (since they are never directly edited by humans, but rather are essentially build artefacts).

You could build them yourself if you have `npm` installed by simply running `npm install`.

Failing that, if you installed _dash-bootstrap-components_ those files will have been packaged with the source. You could find out where its been installed and copy them across from there into your working directory and that should work ok.

If you're not sure where _dash-bootstrap-components_ has been installed, you could run this:

```
python -c "from dash_bootstrap_components import __file__; print(__file__);"
```

The `_components` directory at the same level as the file returned by the above command should have all the auto-generated files, including `metadata.json` and `dash_bootstrap_components.min.js`.

Hopefully one of those options should work for you, let me know if you're having trouble.

**Comment by arthurdelaitre** [comment]
Hi @tcbegley 

Thanks for your response. I resolved the PyInstaller issue by providing PyInstaller with a additional hook file. So now I can use the version installed by conda.

It's working great, thanks !
