### ISSUE TITLE
dash-table dropdown cells

### ISSUE THREAD

**Issue by MUBTAAB** [facultyai/dash-bootstrap-components#243]
Hi! 
I realized that using bootstrap css breaks the [dash-table dropdown cells](https://dash.plot.ly/datatable/dropdowns). 
The issue can easily be resolved by adding this line to the end of the css:
```
.Select-menu-outer {
display : block !important;
}
```

**Comment by tcbegley** [comment]
Thanks for reporting. Since we don't maintain Bootstrap CSS, we just use it to style components, I don't think there's much we can do to fix this, sorry. The fix likely has to come from dash-table itself.

I would recommend you raise this on the [dash-table repo](https://github.com/plotly/dash-table) in case they can better diagnose and fix the problem, and maybe also post your solution on [this Plotly forum thread](https://community.plot.ly/t/dropdown-in-tables-with-bootstrap-stylesheets/26903) so that others can take advantage of your workaround.

**Comment by MUBTAAB** [comment]
Hi, 
Sadly the issue with the workaround was already posted [here](https://github.com/plotly/dash-table/issues/221) and the Dash team already closed it since "a css based solution was found".

**Comment by tcbegley** [comment]
Closing this as it's a result of a clash between Bootstrap CSS and _dash-table_, neither of which we have the ability to change. Sorry we can't be more help.

**Comment by vsisl** [comment]
Hi,
thanks a lot for creating dash_bootstrap_components! dbc layout makes my life so much easier and other dbc components bring new possibilities to my apps. 

@tcbegley I understand the reason to close this issue _without fixing it_.

However, I think it would be a good idea to create a section in [documentation](https://dash-bootstrap-components.opensource.faculty.ai/docs/), where you would warn users about possible conflicts between the bootstrap css stylesheet and dash components (core components, html components, dash_table). Especially dash_table caused me a lot of headaches. As far as I know, one should always use 

```
.dash-table-container .row {
    display: block;
    margin: 0;
}
```

to ensure proper rendering (width) of the table and 

```
.Select-menu-outer {
    display : block !important;
}
```

to properly render dropdowns in table's cells.

**Comment by tcbegley** [comment]
Hi @vsisl 

Thanks for the suggestion, I've been thinking for a while to add a FAQs section or similar to the docs, and this is definitely the sort of thing that should be included. Haven't had time recently unfortunately, but will try to prioritise it in the future.
