### ISSUE TITLE
dbc.Select() should allow individual style options 

### ISSUE THREAD

**Issue by flyingcujo** [facultyai/dash-bootstrap-components#275]
Allowing the ability to allow style options in dbc.Select components would allow similar formatting features allowed by dbc.Dropdownmenuitem() - i.e. set active, format font color, etc - without the need to handle callbacks for each item listed.

**Comment by tcbegley** [comment]
Hey @flyingcujo 

Thanks for the suggestion, but it's actually not possible because the select that gets rendered is a native browser form element rather than styled HTML.

One thing we would plausibly add is support for [option groups](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup), which would allow you to have headed sections in the select. But working out how to support that with the current interface would be non-trivial.

**Comment by MM-Lehmann** [comment]
How trivial would it be including the `title` option attribute as supported by `dcc.dropdown`?
Or maybe supplying `dbc.dropdown` would be easier?

**Comment by tcbegley** [comment]
Hey @MM-Lehmann 

Looks like it's fairly straightforward to support this, adding it in #389

**Comment by tcbegley** [comment]
Adding `title` to each option is now possible as of version 0.10.2. As mentioned earlier, the amount of additional styling we can do is very limited. After thinking a bit about option groups I've decided not to prioritise it, hence I will close this issue for now.
