### ISSUE TITLE
Select.value/label can't updated from callback

### ISSUE THREAD

**Issue by ieipi** [facultyai/dash-bootstrap-components#284]
I have a Select component and want to update its label and value from callback.
1. options = [{'label':'all', 'value':'all'}, {'label':'item-1', 'value':'item-1'}, ]
2. the Select component showed 'all' by default
3. then I changed its value from 'all' to 'item-1' in the page UI.
4. then I triggered a callback, and within the callback i updated its 'value' to 'all';
however, the page still shows 'item-1' and not change from appearance;
but behind the scene its 'value' property already updated to 'all'
so here the appearance and 'value' not consistent

**Comment by tcbegley** [comment]
Hi @ieipi 

Can you check which version of _dash-bootstrap-components_ you are running?

```
python -c "from dash_bootstrap_components import __version__; print(__version__)"
```

There was a change in the latest version which might help with this, so if you don't see `0.7.2` after running the above try upgrading

```
pip install -U dash-bootstrap-components
```

If you have the latest version and you're still having problems could you maybe share a code snippet that reproduces the problem?

**Comment by ieipi** [comment]
thanks @tcbegley , it works after update!
can you give more detail why it happened before?

**Comment by tcbegley** [comment]
Great glad to hear it!

You can check out the changes in #270 for full details, but essentially the problem was that the component initialised its value correctly from the backend, and would send new values to the backend when modified in the ui, but was not re-rendering when the backend value changed. 

That meant if the value changed for any reason other than a new value being selected in the component (e.g. by being set in a callback) the front-end view wouldn't reflect it, precisely as you were seeing.
