### ISSUE TITLE
dbc.Button not loading new href url

### ISSUE THREAD

**Issue by riobranham** [facultyai/dash-bootstrap-components#318]
- dash version: `1.0.1`
- dash-bootstrap-components version: `0.7.2`
- components affected by bug: `dbc.Button`

### What is happening?

Using a dbc.Button with an href to a new url in the dash app. When the button is selected it redirects the url in the browser but does not reload the page. The new page appears only after selecting refresh in the browser (Chrome). This only started happening recently. Without any changes to the code the button stopped working, previously this was not a problem.

### What should be happening?

Automatically load new url page.

### Code

```python
@app.callback(Output('page_content', 'children'), [Input('url', 'pathname')])
def display_page(pathname):
    if pathname is None:
        pathname = '/'
    pages = {
        '/': IndexPage.layout,
        '/other-page': other-page.layout
    }
    if pathname not in pages:
        raise ValueError(f'Missing route {pathname}')
    return pages[pathname]()

```

### Error messages

None

**Comment by tcbegley** [comment]
Hi @riobranham 

Thanks for reporting. I wasn't able to reproduce the error with the following code and library versions

```
dash==1.0.1
dash-bootstrap-components==0.7.2
dash-core-components==1.0.0
```

```python
import dash
import dash_bootstrap_components as dbc
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dcc.Location(id="url"),
        dbc.Button("Page 1", href="/page-1"),
        dbc.Button("Page 2", href="/page-2"),
        html.Div(id="output"),
    ]
)


@app.callback(Output("output", "children"), [Input("url", "pathname")])
def serve_content(pathname):
    return f"Viewing page {pathname}"


if __name__ == "__main__":
    app.run_server(debug=True)
```

However, I suspect that the most likely culprit here is the change in the way that `dcc.Location` works in `dash-core-components==1.8.0`. Sure enough the above example stops working if I update `dash-core-components` to `1.8.0`. Could you check which version of `dash-core-components` you have installed?

```
python -c "from dash_core_components import __version__; print(__version__)
```

If you do have version `1.8.0` you should revert to `1.0.0`, which is the one designed to be used with `dash==1.0.1`, or alternatively update `dash`.

If that's not the problem let me know, and maybe try running my example to see if you have the same problems.

**Comment by tcbegley** [comment]
Closing due to no response. Please reopen if you're still having problems.

**Comment by gaceladri** [comment]
Hello, 

I am having the same issue here. I have reverted to 1.0.0 and installed those versions that you specified, but it's not working neither. The path to the issue was the same, after rebooting the computer, it stopped to work. Now when I click on the button nothing happens.

**Comment by tcbegley** [comment]
Hi @gaceladri 

Could you post the code that isn't working, and also just confirm explicitly which versions of the Dash libraries you have. If you're using a Unix based operating system you could do something like

```
pip list | grep dash
```

**Comment by gaceladri** [comment]
@tcbegley Thanks for your fast response. Here are the dash libraries on my env
`dash                      1.0.1         
dash-bootstrap-components 0.7.2         
dash-core-components      1.0.0         
dash-html-components      1.0.0         
dash-renderer             1.0.0         
dash-table                4.0.1`

**Comment by gaceladri** [comment]
@tcbegley Sorry I didnt read about the code. 

```
search_bar = dbc.Row(
    [
        dbc.Col(dbc.Input(type="msg_input", placeholder="Search here and press the button 'Search'!", debounce=True, style={
                'border-radius': '.5rem'})),
        dbc.Col(
            dbc.Button("Search", id="send_button",
                       color="primary", className="ml-2"),
            width="auto",
        ),
    ],
    no_gutters=True,
    className="ml-auto flex-nowrap mt-3 mt-md-0",
    align="center",
)
```

```
chat_page = html.Div([
    dbc.Navbar(
        [
            html.A(
                # Use row and col to control vertical alignment of logo / brand
                dbc.Row(
                    [
                        dbc.Col(html.Img(src=dash_app.get_asset_url(
                            image_chat), height="29px")),
                        dbc.Col(dbc.NavbarBrand(
                            "blabla", href="/", className="ml-2")),
                    ],
                    align="center",
                    no_gutters=True,
                ),
                href="/",
            ),
            dbc.NavbarToggler(id="navbar-toggler"),
            dbc.Collapse(search_bar, id="navbar-collapse", navbar=True),
        ],
        color="dark",
        dark=True,
    ),
    html.Div([
        html.Span(' ', style={'font-weight': 'bold'}),
        html.A('',
               href=''),
        html.A('...'),
        html.Br(),
        html.Br(),

        html.Ul([html.Li(x) for x in questions_list[0:5]])
    ], id='conversation',  style={'border-radius': '10px',
                                  'background-color': 'white',
                                  'margin': '50px',
                                  'margin-top': '35px',
                                  'padding': '35px',
                                  'padding-left': '25',
                                  'box-shadow': '3px 1px 10px lightgrey',
                                  'overflow-y': 'scroll'})],
    id='screen',
    style=SIDEBAR_STYLE)
```


```
@dash_app.callback(
    Output(component_id='conversation', component_property='children'),
    [Input(component_id='send_button', component_property='n_clicks')],
    state=[State(component_id='msg_input', component_property='value')])
def update_conversation(click, text):
    if click != 0:
    ###
```

**Comment by tcbegley** [comment]
Hi @gaceladri,

Sorry for slow response, been busy the last few days.

I wasn't able to run your code, as there are some references to variables that aren't defined in the snippets you posted.

Instead I made the following simple example and tested it with the versions of the libraries that you posted above, I didn't have any issues. Could you try running it and see if you have the same problems?

```python
import dash
import dash_bootstrap_components as dbc
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dcc.Location(id="url"),
        dbc.Button("Page 1", href="/page-1"),
        dbc.Button("Page 2", href="/page-2"),
        html.Div(id="output"),
    ],
    className="p-5",
)


@app.callback(Output("output", "children"), [Input("url", "pathname")])
def set_content(pathname):
    return f"Currently viewing {pathname}"


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by gaceladri** [comment]
@tcbegley Your example works. My fault was that I misplaced the `id=` and the `type=` of the button when writing. Sorry, my fault. The current code is working properly again. Thanks for your appreciable time.

In my example was:
```

 dbc.Col(dbc.Input(type="msg_input", placeholder="Search here and press the button 'Search'!", debounce=True, style={
                'border-radius': '.5rem'}))
```

and should be:

```
 dbc.Col(dbc.Input(id="msg_input", type="seach", placeholder="Search here and press the button 'Search'!", debounce=True, style={
                'border-radius': '.5rem'})),
```

Sorry!

**Comment by PeterKoppelman** [comment]
I'm having issues with a submit button. I'm using the code from dbc for the simple sidebar. There are four options on the left. One is to send us a comment (an email). I have all of the code written, the screen looks good, but I can't get the submit button to do anything. I don't think that the callback is working, but I can't tell. The following is a snippet from the simple sidebar code:

`@app.callback(
    [Output(f"page-{i}-link", "active") for i in range(1, 4)],
    [Input("url", "pathname")],
)
def toggle_active_links(pathname):
    if pathname == "/":
        # Treat page 1 as the homepage / index
        return True, False, False
    return [pathname == f"/page-{i}" for i in range(1, 4)]


@app.callback(Output("page-content", "children"), 
    [Input("url", "pathname")]
)
def render_page_content(pathname):
    if pathname in ["/", "/page-1"]:
        return welcome.welcome

    elif pathname == "/page-2":
        return calc_portfolio.get_data

    elif pathname == "/page-3":
        return contact_us.email

    elif pathname == '/page-4':
        return html.P('Welcome to the FAQ Page')
`



the following is my code for the comment screen (contact_us.py):


`import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output, State

import smtplib
import mimetypes
from email.mime.multipart import MIMEMultipart
from email import encoders
from email.mime.audio import MIMEAudio
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.text import MIMEText

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

email = html.Div(
        [ 
            dbc.Form(
            [
                dbc.FormGroup(
                    [
                    dbc.Label('To send us a comment please fill out the information below'),
                    html.Br(),
                    dbc.Label('Name:'),
                    dbc.Input(
                        type = 'text',
                        id = 'name',
                        minLength = 3,
                        maxLength = 100,
                        valid = True,
                        style = {'width': 400}
                        ),
                    ],
                ),
                dbc.FormGroup(
                    [
                        dbc.Label('Email address:'),
                        dbc.Input(
                            type="email", 
                            id='email-addr', 
                            minLength = 5,
                            maxLength = 30,
                            valid = True,
                            style = {'width': 400}
                        ),
                    ],
                ),
                dbc.FormGroup(
                    [
                        html.Br(),
                        html.Br(),
                        dbc.Label('Please type your comment below:'),
                        html.Br(),
                        dbc.Label('Minimum 10 characters, maximum 1,000 characters'),
                        dbc.Textarea(
                            # type = 'text',
                            id = 'comment',
                            maxLength = 1000,
                            required = True,
                            rows = 10,
                            spellCheck = True,
                            valid = True
                        ),
                    ],
                ),
            dbc.Button('Submit',
                id = 'submit-email',
                color = 'primary',
                n_clicks = 0
            ),
        ],
    ), html.Div(id = 'email-message'),
])

@app.callback(
    [Output('email-message', 'children')],
    [Input('submit-email', 'n_clicks')],
    [State('name', 'text'),
    State('email-addr', 'email'),
    State('comment', 'text')]
)

def on_button_click(n_clicks, test_name, email_addr, test_comment):
    # if n_clicks is None:
    #     pass

    print('in sendmail function')
    msg = MIMEMultipart()
    msg["From"] = email_addr
    msg["To"] = 'pkoppelman@yahoo.com'
    msg["Subject"] = "Robo Investing Question"
    body = MIMEText('This is a test of the robo investing email system')
    msg.attach(body)

    ctype, encoding = mimetypes.guess_type(email_reference.filetosend)
    if ctype is None or encoding is not None:
        ctype = "application/octet-stream"

    maintype, subtype = ctype.split("/", 1)

    if maintype == "text":
        fp = open(email_reference.filetosend)
        # Note: we should handle calculating the charset
        attachment = MIMEText(fp.read(), _subtype=subtype)
        fp.close()
    elif maintype == "image":
        fp = open(email_reference.filetosend, "rb")
        attachment = MIMEImage(fp.read(), _subtype=subtype)
        fp.close()
    elif maintype == "audio":
        fp = open(email_reference.filetosend, "rb")
        attachment = MIMEAudio(fp.read(), _subtype=subtype)
        fp.close()
    else:
        fp = open(email_reference.filetosend, "rb")
        attachment = MIMEBase(maintype, subtype)
        attachment.set_payload(fp.read())
        fp.close()
        encoders.encode_base64(attachment)
   # attachment.add_header("Content-Disposition", "attachment", filename=email_reference.filetosend)
    # msg.attach(attachment)

    # Send the email - if you get an error that says Username and Password not accepted, please go to the 
    # gmail account that is sending the email and choose 'Less secure app access'. Gmail does not like
    # smtplib - PK March 25, 2020
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.ehlo()
        server.starttls()
        server.login(email_reference.emailfrom, email_reference.password)
        server.sendmail(email_reference.emailfrom, email_reference.distribution_list, msg.as_string())
        server.close()
        message = True
    except:
        message = False

    return message
`

**Comment by tcbegley** [comment]
Hey @PeterKoppelman 

There's some problem in your callback definition, the properties `text` and `email` that you're using in `State` don't exist, you want `value ` for all of them:

```python
[
    State("name", "value"),
    State("email-addr", "value"),
    State("comment", "value"),
],
```

I couldn't debug futher because I don't know what `email_reference` is, but hopefully that helps.

Btw, if you run your app in debug mode this sort of thing pops up in the browser window in Dash's debug tools. Just do something like

```python
app.run_server(debug=True)
```

**Comment by PeterKoppelman** [comment]
Thank you for responding. I've changed the state to value and nothing changes. app.run_server(debug=True) was set in the calling program. I'm not sure where I'm supposed to get. The round blue circle that dash provides tells me that there are no errors and shows me the callbacks, but I'm not sure what I'm looking for. If I put in print statement at the top of my function that just says print('in function'), I get nothing. I'm using windows 10 so I figured that I'd get the print output to windows powershell. But I get nothing.
I'm calling this program from another (app.py). In add,py I have the statement:elif pathname == "/page-3":        return contact_us.email
This calls the program contact_us.email. Could there be an issue with this or is there something wrong with the way that I'm using the submit button?
Thanks in advance...
Peter Koppelman 

    On Monday, July 6, 2020, 05:01:14 AM EDT, Tom Begley <notifications@github.com> wrote:  
 
 


Hey @PeterKoppelman

There's some problem in your callback definition, the properties text and email that you're using in State don't exist, you want value  for all of them:
[
    State("name", "value"),
    State("email-addr", "value"),
    State("comment", "value"),
],
I couldn't debug futher because I don't know what email_reference is, but hopefully that helps.

Btw, if you run your app in debug mode this sort of thing pops up in the browser window in Dash's debug tools. Just do something like
app.run_server(debug=True)

**Comment by PeterKoppelman** [comment]
Tom -
The following is some of my code. I'm using the simple sidebar. I've got 4 options for someone. The third is to send us an email. The screen looks good, but I the send button still doesn't work.
This code is for a capstone class in Python programming at New York University. I started using dash about 1.5 years ago after writing a final project for an intermediate python class. My thought was that Dash was a great and efficient way to distribute information. What I didn't like about Dash was trying to create a front end for people to use. It's a little clunky. That's what I like about dash bootstrap. The front end is really nice. My problem is that I seem to be a knucklehead when it comes to getting different programs to work with each other (see below). I'm also having problems with some of your example code. It doesn't seem to work out of the box for me. 

I do really like the possibilities of the combination of dash bootstrap, dash and python. It's really strong. I think that you need to strengthen your examples and go deeper into things (as an example, I can't be the only person having problems with the submit button). My class ends the middle of August. I'll help out going through all of the examples on your website and tell you the ones that I have issues with. My feedback can only make the website stronger and dash bootstrap better/cooler.
My code is below. I start out with a 'simple sidebar' code snippet. Basically right out of the dash bootstrap example. The only thing changed were the return statements.
@app.callback(    [Output(f"page-{i}-link", "active") for i in range(1, 4)],    [Input("url", "pathname")],)def toggle_active_links(pathname):    if pathname == "/":        # Treat page 1 as the homepage / index        return True, False, False    return [pathname == f"/page-{i}" for i in range(1, 4)]

@app.callback(Output("page-content", "children"),     [Input("url", "pathname")])def render_page_content(pathname):    if pathname in ["/", "/page-1"]:        return welcome.welcome
    elif pathname == "/page-2":        return calc_portfolio.get_data
    elif pathname == "/page-3":        return contact_us.email
    elif pathname == '/page-4':        return html.P('Welcome to the FAQ Page')

if __name__ == "__main__":    app.run_server(debug=True)

The following is my code for contact_us.email. I just create the screen and want to send an email when someone presses submit. I've played around with a few things to show that the code gets into the callback and the function.
import dashimport dash_bootstrap_components as dbcimport dash_core_components as dccimport dash_html_components as htmlfrom dash.dependencies import Input, Output, State
import smtplibimport mimetypesfrom email.mime.multipart import MIMEMultipartfrom email import encodersfrom email.mime.audio import MIMEAudiofrom email.mime.base import MIMEBasefrom email.mime.image import MIMEImagefrom email.mime.text import MIMEText
app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])
email = html.Div(        [             dbc.Form(            [                dbc.FormGroup(                    [                    dbc.Label('To send us a comment please fill out the information below'),                    html.Br(),                    dbc.Label('Name:'),                    dbc.Input(                        type = 'value',                        id = 'name',                        minLength = 3,                        maxLength = 100,                        valid = True,                        style = {'width': 400}                        ),                    ],                ),                dbc.FormGroup(                    [                        dbc.Label('Email address:'),                        dbc.Input(                            type="value",                             id='email-addr',                             minLength = 5,                            maxLength = 30,                            valid = True,                            style = {'width': 400}                        ),                    ],                ),                dbc.FormGroup(                    [                        html.Br(),                        html.Br(),                        dbc.Label('Please type your comment below:'),                        html.Br(),                        dbc.Label('Minimum 10 characters, maximum 1,000 characters'),                        dbc.Textarea(                            id = 'comment',                            maxLength = 1000,                            required = True,                            rows = 10,                            spellCheck = True,                            valid = True                        ),                    ],                ),            dbc.Button('Submit',                id = 'submit-email',                color = 'primary',                n_clicks = 0            ),        ],    ), html.Div(id = 'email-message')])

@app.callback(    [Output('email-message', 'children')],    [Input('submit-email', 'n_clicks')],    [State('name', 'value'),    State('email-addr', 'value'),    State('comment', 'value')])
def on_button_click(n_clicks, test_name, email_addr, test_comment):    if n_clicks is None:        print('n clicks is 0')    else:        print('n_clicks is not 0')
    print('in sendmail function')

I figure that if one of the print statements work, then I'm home free to send the email.


 
Peter (917) 826-9295 (cell) 

    On Monday, July 6, 2020, 05:01:14 AM EDT, Tom Begley <notifications@github.com> wrote:  
 
 


Hey @PeterKoppelman

There's some problem in your callback definition, the properties text and email that you're using in State don't exist, you want value  for all of them:
[
    State("name", "value"),
    State("email-addr", "value"),
    State("comment", "value"),
],
I couldn't debug futher because I don't know what email_reference is, but hopefully that helps.

Btw, if you run your app in debug mode this sort of thing pops up in the browser window in Dash's debug tools. Just do something like
app.run_server(debug=True)

**Comment by wernerolaf** [comment]
when using example from above in my case callback is not triggered when url change, my versions of dash

dash | 1.17.0 | 1.17.0
-- | -- | --
dash-bootstrap-components | 0.10.7 |  
dash-core-components | 1.3.1 | 1.3.1
dash-html-components | 1.0.1 | 1.0.1
dash-renderer | 1.1.2 | 1.8.3
dash-table | 4.4.1 | 4.4.1

I have similiar problems when using dbc compponents like NavLink


import dash
import dash_bootstrap_components as dbc
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dcc.Location(id="url"),
        dbc.Button("Page 1", href="/page-1"),
        dbc.Button("Page 2", href="/page-2"),
        html.Div(id="output"),
    ],
    className="p-5",
)


@app.callback(Output("output", "children"), [Input("url", "pathname")])
def set_content(pathname):
    return f"Currently viewing {pathname}"


if __name__ == "__main__":
    app.run_server(debug=True)

**Comment by tcbegley** [comment]
Hi @wernerolaf 

Looks like you have pretty old version of the Dash component libraries. Can you

```
pip install -U dash
```

and try again? Working for me with

```
dash                      1.17.0
dash-bootstrap-components 0.10.7
dash-core-components      1.13.0
dash-html-components      1.1.1
dash-renderer             1.8.3
dash-table                4.11.0
```
