### ISSUE TITLE
Can't install any version above 0.8.0 via pip

### ISSUE THREAD

**Issue by nfrik** [facultyai/dash-bootstrap-components#320]
Please fill out the below information as much as possible.

- dash version: `1.9.0`
- dash-bootstrap-components version: `0.8.3`
- components affected by bug: dash

### What is happening?

Can't install dbc 0.8.3, 0.8.2 and 0.8.1 with pip for python 3.6.10

Installation is interrupted with the following error:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 436: ordinal not in range(128)
`
### What should be happening?

Should be able to install new version with: pip install dash_bootsrap_components

### Code

 pip install dash_bootsrap_components

```python
NA
```

### Error messages

```bash
bash# pip install dash_bootstrap_components
Collecting dash_bootstrap_components
  Using cached dash-bootstrap-components-0.8.3.tar.gz (99 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp0e73vggl
       cwd: /tmp/pip-install-v375h1k6/dash-bootstrap-components
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-_cffo22w/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 148, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-_cffo22w/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 128, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-_cffo22w/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 250, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-_cffo22w/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 30, in <module>
      long_description=_get_long_description(),
    File "setup.py", line 23, in _get_long_description
      return f.read()
    File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 436: ordinal not in range(128)
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp0e73vggl Check the logs for full command output.
```

**Comment by tcbegley** [comment]
Hey @nfrik 

Thanks for reporting this. The problem is with [this line](https://github.com/facultyai/dash-bootstrap-components/blob/master/setup.py#L22) in the setup script which is loading some text to populate the metadata of the package. I didn't realise before that the `encoding` argument of `open`, which is unspecified in the script, has a [platform dependent default value](https://docs.python.org/3/library/functions.html#open). It seems that on your system Python is defaulting to trying to interpret the text as ascii, but there are a few non-ascii characters in there.

I just opened #322 to address this, it both explicitly sets the encoding when reading the file, but also removes non-ascii characters that were causing this to fail. That will make it into the next release which I will bump up my todo list because of this issue.

In the meantime, you might be able to workaround this by enabling UTF-8 mode in your Python interpreter. Note that I haven't been able to easily test this on my system, but if you try it let me know if it works.

```bash
python -X utf8 -m pip install dash-bootstrap-components
```

**Comment by tcbegley** [comment]
@nfrik I just made a prerelease with the changes of #322 included, let me know if you have the same issues installing

```
pip install dash-bootstrap-components==0.8.4rc1
```

**Comment by nfrik** [comment]
@tcbegley Thanks a lot! It seems to be working fine now.
