### ISSUE TITLE
dcc.Graph causes flickering when used with bootstrap

### ISSUE THREAD

**Issue by audetto** [facultyai/dash-bootstrap-components#349]
Please fill out the below information as much as possible.

```
dash                 1.9.1
dash-bootstrap-components    0.9.1
dash-core-components 1.8.1
dash-html-components 1.0.2
dash-renderer        1.2.4
dash-table           4.6.1
```

### What is happening?

I have built a dashboard using dash bootstrap components and a few graphs.
What happens is that for some combination of elements on the page the graphs (there are 2) get resized marginally when the mouse is moved over the page (without clicking). This in turns causes scrollbars to appear and disappear causing an overall flickering effect on the page that becomes annoying.

They resize when then mouse enters and exits their area, not when it is moved fully inside or outside.

This happens only on a maximised window.
Moreover, by adding or removing some elements of the layout (even in unrelated areas) the effect is triggered on un-triggered, so what I do I rearrange things till the effect stops.

I've seen this in 2 separate dashboards and I was not able to find what really triggers it (both use dash bootstrap components, dbc.Rows and dbc.Cols).

### What should be happening?

Components should not resize constantly when the mouse is moved around.

### Code

Unfortunately this happens at work and I have not been able to take it out.

I've opened an issue in dash as this sits somewhere in the middle: the interaction between dash and bootstrap.

https://github.com/plotly/dash/issues/1168

**Comment by tcbegley** [comment]
Hey @audetto,

Thanks for reporting. Unfortunately it's pretty hard to help without being able to reproduce the behaviour, but I will keep an eye out for this behaviour and monitor the other issue you opened.

Are you using any additional CSS in your app or is it just Bootstrap?

**Comment by tcbegley** [comment]
Closing due to no response and inability to reproduce the reported behaviour. Please reopen if you can recreate this or continue to see the problem.

**Comment by mazeenmuhammed** [comment]
![image](https://user-images.githubusercontent.com/47627286/90660454-8fc65180-e263-11ea-92a4-b07611947643.png)

I have three tabs and in one of the tabs there is a drop down.
2 graphs i have printed next to each other.
Once i run the app and toggle to this tab ,  there is slight flickering of screen  but when i click on the drop down entire layout starts to flicker like crazzzyy.

**Comment by tcbegley** [comment]
Hi @mazeenmuhammed 

Would it be possible for you to share your code so I can see if I can reproduce this?

**Comment by mazeenmuhammed** [comment]
Hey that flickering stopped. I don't know why and how it was flickering whenever I used to hover over the drop down. But I think it stoped cause I set the width of the DBC.row which was displaying the graphs in two columns to 100%

**Comment by schlich** [comment]
I am experiencing this bug again @tcbegley

**Comment by audetto** [comment]
It does look exactly the same as what I had when I opened this issue.
Since, things have settled, but cannot say exactly why, how and if.

**Comment by tcbegley** [comment]
@schlich thanks for sharing this. I tried running your app but don't have `data/data.h5`, are you able to share it so I can see if I can reproduce the problem?

That said I notice something in your example, it seems the vertical scrollbar appearing is causing the width of the page to shrink and hence the flickering. Perhaps the appearance of the modebar in the plot is causing the graph container to become slightly taller and hence cause the scrollbar to appear? It would be interesting to resize your window to reduce the vertical height and see if that changes the behaviour at all.

I also notice you have a horizontal scrollbar which suggests the app contents are wider than the viewport. This is likely because you are using `dbc.Row` (which sets negative margins) without wrapping it in `dbc.Container`. Replacing the outer `html.Div` [here](https://github.com/schlich/psychoanalyze/blob/master/dashboard.py#L13) with a `dbc.Container(..., fluid=True)` might help.

**Comment by schlich** [comment]
It looks like the container did the trick! I probably should have read the documentation a little more thoroughly :)

I can email you the .h5 (to the email listed on your profile) if you'd like it in order to reproduce, just let me know.  As previously mentioned in the thread, it only really happened when I was full screen.  my display resolution is 1920x1080 if that helps, on a Lenovo ThinkBook 14s-IWL (14ish inch screen)

**Comment by tcbegley** [comment]
Great! If the fix works then there's no need to send me the data.

I will maybe rewrite the layout docs to emphasise the need for containers when using rows and cols.
