### ISSUE TITLE
Multi-Value Select

### ISSUE THREAD

**Issue by acoque** [facultyai/dash-bootstrap-components#364]
Hello there !

First, thanks for the nice work you've done. It's realy easy to design a nice-looking dashboard using this package.

I'm in the exact same situation than bearch (#174), except than I'm using dbc.Select components instead of a dbc.Dropdown (dbc.Select didn't exist when #174 was open by bearsh) and I was then wondering if you were planning to implement multivalue support for this component (for instance in the same way than dcc.Dropdown works, with a *multi=True* flag).

I could use dcc.Dropdown as it is but it doesn't work well inside of an InputGroup with an InputGroupAppend (as you can see on the following picture).
![select](https://user-images.githubusercontent.com/35691279/81147904-88f92480-8f7b-11ea-84ed-3684c0a06842.png)

Thanks ;)

(Otherwise, maybe I should try to modify the style of dcc.Dropdown 🤔)

**Comment by tcbegley** [comment]
Hey @acoque 

The `Select` component just renders a HTML `<select>`, which does have a `multiple` option, but it doesn't render quite like you might expect on most browsers, it's usually a scrolling list box rather than a dropdown style selector. Take a look [here](https://getbootstrap.com/docs/4.4/components/forms/#select-menu) for example (you might need to scroll down a bit to get to the multiple example).

I think you can write some custom CSS without too much trouble. It looks like you're using the dash-bootstrap-css stylesheets already? In which case some custom CSS like this ought to do the trick

```css
.dash-bootstrap .input-group-prepend + div {
  flex-grow: 1;
}

.dash-bootstrap .input-group-prepend + div .Select-control {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
```

I just tried that out with this simple app

```python
import dash
import dash_bootstrap_components as dbc
import dash_core_components as dcc

# note no dbc.themes.BOOTSTRAP, I have CSS in my assets/ folder
app = dash.Dash()

app.layout = dbc.Container(
    dbc.InputGroup(
        [
            dbc.InputGroupAddon("Test", addon_type="prepend"),
            dcc.Dropdown(
                options=[{"label": f"Item {i}", "value": i} for i in range(10)]
            ),
        ]
    ),
    className="dash-bootstrap p-5",
)


if __name__ == "__main__":
    app.run_server(debug=True)
```

With both the above custom CSS and dash-bootstrap-css in my `assets/` folder I get

![image](https://user-images.githubusercontent.com/15220906/81331807-116de700-909a-11ea-9c7b-a26c37f6ff86.png)

**Comment by acoque** [comment]
Hello @tcbegley 

I feel like an idiot not to find out dcc.Select only renders an HTML `<select>`... And as u say, it looks weird in most of browsers (with the multiple option set to true).

About the dash-bootstrap-css stylesheet, well, I just added the "dash-bootstrap className stuff" cause I see that in an issue or some random commit but I didn't download the stylesheet and put it into my assets folder - I thought it was included in the main project (but again, I was wrong).
But I now use it properly (I took a look to the project [README](https://github.com/tcbegley/dash-bootstrap-css) and it seems to work well. By the way, you're custom CSS works fine too. Thanks a lot mate and have a nice day !
