### ISSUE TITLE
Allow float value for width parameter of Col

### ISSUE THREAD

**Issue by gioxc88** [facultyai/dash-bootstrap-components#383]
at the moment the width is specified as number of columns in a grid of 12.
It should be easy to implement something like this by default

```
if isinstance(width, float):
    width= round(12 * width)
```

**Comment by tcbegley** [comment]
Hey @gioxc88 

Thanks for the suggestion. Is there a reason this should be part of `Col` rather than just letting the user do `dbc.Col(width=round(12 * width))`?

I'm hesitant to include it to be honest because I think it might lead to confusing results. For example `width=0.3` would be twice the width of `width=0.2`. Forcing users to think in terms of the grid system means no nasty surprises like this.

**Comment by gioxc88** [comment]
I see your point, it would just be less verbose if it was already implemented by default, and since I found myself using the `Col` a lot it would have been useful. Also this wouldn't change the current behavior but it would extend it.

But thank you for the answer anyway!!

**Comment by tcbegley** [comment]
If it's something you've found yourself doing a lot, you could always either subclass `Col` or create a factory function. Something like

```python
class MyCol(dbc.Col):
    def __init__(self, *args, **kwargs):
        if "width" in kwargs and isinstance(kwargs["width"], float):
            kwargs["width"] = round(kwargs["width"] * 12)
        super().__init__(*args, **kwargs)
```

or

```python
def make_col(*args, **kwargs):
    if "width" in kwargs and isinstance(kwargs["width"], float):
        kwargs["width"] = round(kwargs["width"] * 12)
    return dbc.Col(*args, **kwargs)
```

either of those would help keep your code less verbose.

**Comment by tcbegley** [comment]
I've decided not to implement this for the aforementioned reasons, so will close this now. I hope the snippets above present an acceptable compromise for those who want this functionality.
