### ISSUE TITLE
No vertical scrollbar with dash_table.DataTable and external_stylesheets=[dbc.themes.BOOTSTRAP]

### ISSUE THREAD

**Issue by acul71** [facultyai/dash-bootstrap-components#399]
Before opening:

dash==1.10.0
dash-bootstrap-components==0.8.0

If I use external_stylesheets=[dbc.themes.BOOTSTRAP] dash DataTable is 
just show a vertical bar but not working with
style_table={
                'maxHeight': '397px',
                'overflowY': 'scroll'
}
or not showing vertical scroll bar at all with:
style_table={
                'maxHeight': '397px',
                'overflowY': 'auto'
}

![Screenshot from 2020-06-09 03-51-07](https://user-images.githubusercontent.com/34693171/84097359-a438d300-aa04-11ea-816f-6674c03e7d46.png)
![Screenshot from 2020-06-09 03-49-57](https://user-images.githubusercontent.com/34693171/84097360-a4d16980-aa04-11ea-8425-502256003cdb.png)

**Comment by tcbegley** [comment]
Hey @acul71 

It's likely this is because `dash-table` and Bootstrap CSS both use a CSS class called `row` and they class. Could you try adding the following CSS to your `assets/` folder?

```css
.dash-table-container .row {
  display: block;
  margin: 0;
}
```

See [here](https://dash.plotly.com/external-resources) for more details on adding custom CSS to Dash apps. Let me know if that resolves the problem.

**Comment by acul71** [comment]
Hey it works.
I used the  css file solution in assets
Many thanks
