### ISSUE TITLE
Dynamic Tooltips causes `Failed to execute 'querySelectorAll' -- not a valid selector`

### ISSUE THREAD

**Issue by qdbp** [facultyai/dash-bootstrap-components#483]
Before opening:

- dash version: `0.17.0`
- dash-bootstrap-components version: `0.10.7`
- components affected by bug: `Tooltip`

### What is happening?

Dynamically created/destroyed tooltips cause frequent errors like:
```
Failed to execute 'querySelectorAll' on 'Document': '17dcd175db8eafeba63e99e724620eb8798dc7d1' is not a valid selector.
```

### Code

```python
from uuid import uuid4

from dash import Dash
from dash.dependencies import Input, Output
from dash_bootstrap_components import Tooltip
from dash_html_components import Button, Div, Span

layout = Div(
    [Button("randomize", id="randomize"), Div(id="holder")],
)

app = Dash("test")
app.layout = layout


@app.callback(
    Output("holder", "children"),
    [Input("randomize", "n_clicks")],
)
def gen_random_span(_):
    s = uuid4().__str__()
    return [
        Span(f"{s[:4]}...", id=s),
        Tooltip(
            f"full description of {s}",
            id=f"trigger{s}",
            target=s,
        ),
    ]


if __name__ == "__main__":
    app.run_server("127.0.0.1", 13337, debug=True)

```

**Comment by tcbegley** [comment]
Hi @qdbp 

Thanks for raising this and including a clear example.

The problem here is that the underlying Reactstrap implementation of the Tooltip searches for the target element using the browser's `document.querySelectorAll` method, and the search string has to be a valid CSS selector string. This is more restrictive than the rules governing HTML ids. Specifically (details [here](https://www.w3.org/TR/CSS21/syndata.html#characters))

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-z0-9] and ISO 10646 characters U+00A1 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, or a hyphen followed by a digit

In the case of your example above, the problem is your dynamically created `id` starts with a number. I fixed the issue by doing something like `s = f"id-{uuid4()}"`.

More generally, when using pattern-matching callbacks and setting the `id` to be a dictionary, dash serialises the dictionary as a JSON string which is again not a valid CSS selector as it contains characters `{}:` and so on. The workaround I've found most effective in this case is to create a wrapper element with an `id` you control. So this example from the Dash docs

```python
new_dropdown = dcc.Dropdown(
    id={
        'type': 'filter-dropdown',
        'index': n_clicks
    },
    options=[{'label': i, 'value': i} for i in ['NYC', 'MTL', 'LA', 'TOKYO']]
)
```

maybe becomes something like

```python
new_dropdown = html.Div([
    html.Div(
        dcc.Dropdown(
            id={
                'type': 'filter-dropdown',
                'index': n_clicks
            },
            options=[{'label': i, 'value': i} for i in ['NYC', 'MTL', 'LA', 'TOKYO']]
        ),
        id=f"dropdown-wrapper-{n_clicks}",
    ),
    dbc.Tooltip(f"Tooltip for dropdown {n_clicks}", target=f"dropdown-wrapper-{n_clicks}")
)
```

Hope that makes sense. I have been looking at alternative ways of attaching tooltips to elements since this problem is a bit annoying, but since it would involve breaking changes to the API it's not something I plan to rush out.

**Comment by tcbegley** [comment]
Closing due to no response. This issue has since been covered in the [new FAQ section](https://dash-bootstrap-components.opensource.faculty.ai/docs/faq/) in the docs. Feel free to reopen if you're still having issues.
