### ISSUE TITLE
Allow radio and checkbox inputs?

### ISSUE THREAD

**Issue by pbugnion** [facultyai/dash-bootstrap-components#50]
At the moment, only the following input types are [allowed](https://github.com/ASIDataScience/dash-bootstrap-components/blob/master/src/components/input/Input.js#L103):

- text
- textarea
- number
- password
- email
- range
- search
- tel
- url
- hidden

Reactstrap explicitly [supports](https://github.com/reactstrap/reactstrap/blob/master/src/Input.js#L66) checkbox and radio inputs as well. Is there a reason those weren't included? There's a comment to the effect that we only want to support types with wide browser support, but checkbox and radio inputs are very widely [supported](https://www.wufoo.com/html5/).

Happy to add those in if we think it's useful. If we do this, we should amend the documentation on input groups (PR #51 ) to document dropdowns.

**Comment by tcbegley** [comment]
The checkbox and radio inputs are included as `Checklist` and `RadioItems` components, both to shadow the implementation in Dash Core Components, and because allowing allowing the input type to be type `radio` or `checkbox` would then require a much more manual construction of the radio buttons or checkboxes that I think would be very difficult to use in Dash callbacks.

**Comment by tcbegley** [comment]
Ah ok, yeah I think that would be useful, particularly to allow use of checkboxes in input groups as in the reactstrap examples.

**Comment by tcbegley** [comment]
Resolved by #134
