### ISSUE TITLE
Why does Collapse require a callback?

### ISSUE THREAD

**Issue by amarvin** [facultyai/dash-bootstrap-components#543]
[Bootstrap Collapse](https://getbootstrap.com/docs/4.3/components/collapse/#example) uses the `data-*` attributes to allow collapsing an element using a button without writing any JavaScript or CSS, but the examples for [`dash_bootstrap_components.Collapse`](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/collapse/) all use server-side callbacks. Are the callbacks really necessary?

Bootstrap Collapse uses attributes `data-toggle` and `data-target` (when using a `<button>` or `href` when using an `<a>`) to define the collapse, but this doesn't seem to work in `dash` -- clicking the button does nothing. Maybe this is a limitation of `dash`? Here's an example to replicate the Bootstrap Collapse example in `dash`:

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])
app.layout = html.Div(
    [
        html.A(
            "Link with href",
            className="btn btn-primary",
            **{
                "data-toggle": "collapse",
                "aria-expanded": "false",
                "aria-controls": "collapseExample",
            },
            href="#collapseExample",
            role="button",
        ),
        html.Div(
            html.Div(
                "Content",
                className="card card-body",
            ),
            className="collapse",
            id="collapseExample",
        ),
    ],
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by tcbegley** [comment]
Hey, good question. The TL;DR version is something like

- It is more flexible
- Callbacks are more idiomatic to Dash than `data-*` attributes
- If the round-trip to the server is too costly you always have the option of writing a clientside callback.

But in some more detail:

The `data-*` attributes are picked up by the JavaScript bundled with Bootstrap which is what enables this functionality, but that JavaScript is (/ was, not true of Bootstrap v5 which is soon coming out) based on jQuery which doesn't play so well with React. That Bootstrap JavaScript is not used by dash-bootstrap-components, we're using reactstrap under the hood which reimplements all of that functionality in React, which is why setting the `data-*` attributes in Dash will not work.

In React using `data-*` attributes to connect components isn't idiomatic (might be possible? not an expert), so if you look at the implementations of `Collapse` in either [reactstrap](https://reactstrap.github.io/components/collapse/) or even [React-Bootstrap](https://react-bootstrap.github.io/utilities/transitions/#collapse) the approach is different, the user manually controls the state which is passed to the Collapse. 

reactstrap has an `UncontrolledCollapse` component which lets you specify a CSS selector and the Collapse will respond to click events on those elements. We could offer something similar to this, but you would lose some flexibility to respond to things other than clicks on particular elements, such as opening a Collapse when a `Graph` is hovered, or in [this example](https://github.com/tcbegley/dash-rq-demo) where the Collapse is used to hide a progress bar after a long-running job is completed. Maybe those use cases are niche, but it's nice to have the option. I also think that a callback is more familiar to the majority of Dash users, especially given the slight syntactic weirdness of `**{"data-*": "value"}`.

Anyway, to your last point, I agree that a round-trip to the server is pretty inefficient for just opening a `Collapse`. It's possible to instead do this with a clientside callback (something I've been meaning to add to the documentation). Like the `data-*` attributes in Bootstrap JS, this doesn't require a round-trip, but is much more idiomatic to Dash, and doesn't compromise on the flexibility of being able to control the state of the `Collapse` with an arbitrary callback.

```python
import dash
import dash_bootstrap_components as dbc
from dash.dependencies import Input, Output, State

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Button("Toggle", id="toggle", className="mb-3"),
        dbc.Collapse(dbc.Card("Content", body=True), id="collapse",),
    ],
    className="p-5",
)

app.clientside_callback(
    """
    function(n_clicks, is_open) {
        return n_clicks ? !is_open : is_open;
    }
    """,
    Output("collapse", "is_open"),
    Input("toggle", "n_clicks"),
    State("collapse", "is_open"),
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by amarvin** [comment]
You are amazing! Thanks for such an informative and quick response. That makes a lot of sense that jQuery-based parts of Bootstrap were excluded to stick to the React/Dash idiomatic approach. That clientside callback is exactly what I need.

I also put an fontawesome icon on the collapse button, and had the callback change to the rotated version of that icon. It's hard  to animate that as a rotation though, but was easy with Bootstrap+jQuery. Not a dealbreaker though!

**Comment by tcbegley** [comment]
Check out [this example](https://github.com/facultyai/dash-bootstrap-components/tree/c05775e6ab883cd1e8e5de1129135ef7c17a60c9/examples/multi-page-apps/sidebar-with-submenus) which does the rotating icons with a bit of extra CSS + a callback on the classNames. It uses serverside callbacks, but I think it should be easy enough to translate to clientside.

**Comment by amarvin** [comment]
Thanks!
