### ISSUE TITLE
dropdown menu button expand on hover

### ISSUE THREAD

**Issue by luiztauffer** [facultyai/dash-bootstrap-components#591]
Hi guys, thanks for this great package!

Is there any easy way to make a dropdown menu button expand `on hover` instead of on click?

**Comment by tcbegley** [comment]
Hey, currently there isn't an easy way to do this I'm afraid. This is mainly because Bootstrap itself only supports opening dropdowns with click events. This is actually [an intentional choice](https://markdotto.com/2012/02/27/bootstrap-explained-dropdowns/#behavior)

I'm reluctant to override design principles of Bootstrap in this library, since it would correspond to unexpected behaviour for those familiar with Bootstrap first and Dash second.

If it helps the [Popover](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/popover/) component supports a hover trigger?

**Comment by luiztauffer** [comment]
The Popover element should work just as well for my purpose, thanks a lot!
