### ISSUE TITLE
bootstrap css blocked

### ISSUE THREAD

**Issue by audetto** [facultyai/dash-bootstrap-components#614]
Since today, my company blocks the css from https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css because of something related to so Cross-Origin Read Blocking.

This happens for the https://dash-bootstrap-components.opensource.faculty.ai/ and for all my dashboards.
Do you know if there is a problem and how to fix it?

**Comment by audetto** [comment]
Thank you.
I suspect the x-origin to be a red herring.
They have simply blocked that website.

**Comment by audetto** [comment]
Would it make sense to automatically ship the css as part of dash-bootstrap without user intervention?

**Comment by tcbegley** [comment]
> Would it make sense to automatically ship the css as part of dash-bootstrap without user intervention?

I don't think so. We deliberately don't do this to give the user flexibility to choose a stylesheet of their choice (e.g. one of the [Bootswatch themes](https://bootswatch.com/)). If we bundled CSS with the library this wouldn't be possible. Since Dash allows you to link local stylesheets anyway I think that's the better solution to issues like this.

**Comment by audetto** [comment]
Thank you.
I was about to ask about themes.

And I believe that the version has to match exactly. So now I need 4.5.2.
