### ISSUE TITLE
Remaining bootstrap components from [getbootstrap.com](https://getbootstrap.com/docs/5.0/components/accordion/)

### ISSUE THREAD

**Issue by USchneid** [facultyai/dash-bootstrap-components#634]
Hello, 
there are some bootstrap components, that are currently not part of the package, such as the 
[accordion](https://getbootstrap.com/docs/5.0/components/accordion/) or the [offcanvas](https://getbootstrap.com/docs/5.0/components/offcanvas/) component. 

Are there plans to realize them in the next time?

Best regards

**Comment by tcbegley** [comment]
Hey,

These are new components in Bootstrap v5, currently dash-bootstrap-components supports v4. This is in part because of the underlying JavaScript libraries that this library is built on, but also because upgrading means making some breaking changes which we don't want to rush into.

That said the plan is to upgrade and release v1 of dash-bootstrap-components with support for Bootstrap 5 later this year.

**Comment by tcbegley** [comment]
These components are available in the v1 beta

```sh
pip install -U --pre dash-bootstrap-components
```
