### ISSUE TITLE
NestedDropdownMenu

### ISSUE THREAD

**Issue by stoufa** [facultyai/dash-bootstrap-components#636]
During a recent project, I needed a version of the [DropdownMenu](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/dropdown_menu/) component that supports nested sub-menus.

The current version of the component doesn't fit my particular need which made me try to build it myself,
the result looks very promising, and I thought it would be great to add it to the component library. 🤓

Unfortunately, I don't have enough time to fully understand the whole project and submit a proper pull request,
this is why I created a separate [repo](https://github.com/stoufa/NestedDropdownMenu) containing all the details needed should someone wants to take a look at my contribution.

Thanks in advance.

**Comment by tcbegley** [comment]
Hi @stoufa 

Thanks for sharing this, it's very cool!

I think as it stands it would be difficult to incorporate into the component library itself since we make heavy use of Reactstrap who are unlikely to modify their components in a way that deviates from Bootstrap too much. While this functionality is cool, it's doing something that's not actually part of the Bootstrap design system.

Perhaps though a version of your app could fit in our [advanced component usage examples](https://github.com/facultyai/dash-bootstrap-components/tree/main/examples/python/advanced-component-usage). I also think that you should post it on the [Plotly forum](https://community.plotly.com/) as I'm sure people there would be interested in this.
