### ISSUE TITLE
When using dbc themes, specifying RangeSlider's tooltip placement as 'top' will freeze browser, if there is not enough space on top of RangeSlider

### ISSUE THREAD

**Issue by hengwang322** [facultyai/dash-bootstrap-components#640]
Before opening:

Please fill out the below information as much as possible.

- dash version: `1.21.0`
- dash-bootstrap-components version: `0.1.3`
- components affected by bug: `dbc.themes.BOOTSTRAP`, `dbc.themes.CYBORG`, etc

### What is happening?

Running the example code and trying to drag the slider will freeze the browser (both Chrome 92.0.4515.131 & Firefox 91.0). This only happens when using one of the themes from dbc, and only happens if RangeSlider is at the very top. My guess is the themes force tooltip to appear on top (where there's nowhere to grow) and lead to undesirable behaviour.  

Using other stylesheets (e.g., `https://codepen.io/chriddyp/pen/bWLwgP.css`) avoid the issue, so is giving RangeSlider enough space (e.g., uncomment line 9). Interestingly, comment out line 10 and thus giving it even less space forces the tooltip to appear below, which also avoid the issue. Although I'm too new to Dash to figure out exactly why.

I imaging this is a pretty low priority bug and probably won't happen in a real case, but for any poor soul who stumps into freezing issue, this might be why.

### Code

```python
import dash_bootstrap_components as dbc
import dash_html_components as html
import dash
import dash_core_components as dcc

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div(children=[
    # html.H1('This is enough space.'),
    html.H5('Slider'),
    dcc.RangeSlider(id="range-slider",tooltip={'placement': 'top'})
])

app.run_server(debug=True)

**Comment by tcbegley** [comment]
Hi @hengwang322 

Thanks for reporting this. I can confirm I can reproduce the issue. Also that it's not some clash with the dash-bootstrap-components JavaScript bundle, I see the same problem when linking Bootstrap CSS manually (see below)

Since this is a problem between `RangeSlider` and Bootstrap CSS, neither of which we maintain here in this repo, I think this will have to be reported over on the [dash-core-components repo](https://github.com/plotly/dash-core-components), would you mind opening up an issue there? I also can't tell exactly what the problem is, but it does look like the component tries to render the tooltip off-screen which causes something to crash.

```python
import dash
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash(
    external_stylesheets=[
        "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    ]
)

app.layout = html.Div(
    children=[
        html.H5("Slider"),
        dcc.RangeSlider(id="range-slider", tooltip={"placement": "top"}),
    ]
)

if __name__ == "__main__":
    app.run_server(debug=True)
```
