### ISSUE TITLE
Checklist in children of Button silences callback

### ISSUE THREAD

**Issue by Ponteaus** [facultyai/dash-bootstrap-components#657]
Please fill out the below information as much as possible.

- dash version: `#1.20.0`
- dash-bootstrap-components version: `#0.11.3`
- components affected by bug: Button, Checklist

### What is happening?

I've placed a Checklist component inside the children arg of a Button component. I then created a callback listening to the checked value of the Checklist, but this callback is never triggered except for the initial call. The example code below generates a single 'None' from the print statement (initial call).

### What should be happening?

Callback should be triggering every time I check or uncheck the checkbox. Example code should generate a string of False, True, False, True, False.... as I check and uncheck the radio item.

### Code

```python
import dash_bootstrap_components as dbc

layout = [
    dbc.Button(
        id='btn_delete',
        disabled=True,
        children=[
            'Delete',
            dbc.Checkbox(
                id='radio_enable_delete',
                checked=False,
            ),
        ],
    ),
]

@app.callback(
    Output('btn_delete', 'disabled'),
    Input('radio_enable_delete', 'checked'),
)
def enable_update(radio_enabled):
    print(radio_enabled)
    return not radio_enabled
```

**Comment by tcbegley** [comment]
Sorry for going quiet on this issue, we were focused on release of v1 and other bug fixes.

I think this would be complicated to support because Bootstrap checkboxes are not really designed to be placed inside a button, they secretly aren't even the browser's native checkboxes, they're simulated with CSS. A checkbox outside of the button is more conventional and should probably be the preferred solution here.
