### ISSUE TITLE
Create handler to extract columnProps correctly

### ISSUE THREAD

**Issue by tcbegley** [facultyai/dash-bootstrap-components#67]
Currently the pipeline for generating docstrings for each of the components (which is also visible as part of the auto-generated api documentation in the docs app) fails on custom prop-types such as `columnProps` as used by `Col`. This would be most robustly resolved by adding a handler to the pipeline that can correctly extract and parse the prop type.

**Comment by AnnMarieW** [comment]
Instead of creating a handler for this, what do you think about combining the `xs, sm, md, lg, xl, xxl` props into the `width` prop?

For example, today you can do this:
```
width = 3 # sets xs breakpoint
width={"size": 3, "order": "last", "offset": 1}

# or set for each of the 6 breakpoints:
sm = 6
sm = {"size": 6, "order": "last", "offset": 1}
lg = 3
lg = {"size": 3, "order": "last", "offset": 1}
```

If it was combined with the  `width` prop, the following would also be valid:
```
width={"sm": 6, "lg": 3}
width={"sm":  {"size": 6, "order": "last", "offset": 1}, "lg": {"size": 3, "order": "last", "offset": 1}}
```
Advantages:
- one prop for the width instead of 7
- the auto-generated documentation would be correct
- allow for PropTypes  to validate properly.

**Comment by tcbegley** [comment]
It's definitely cleaner. My main question is whether you think we can do it in a backwards compatible way?

**Comment by AnnMarieW** [comment]
I suppose that the individual `xs, sm, md, lg, xl, xxl` could still work.   Then if someone set it in both places, then the `width` prop could override anything that was set in the individual breakpoints --  since that is the preferred method.
