### ISSUE TITLE
Dash Bootstrap Components has no attribute Element

### ISSUE THREAD

**Issue by jbatch01** [facultyai/dash-bootstrap-components#678]
- dash version: `2.0.0`
- dash-bootstrap-components version: `0.11.0`
- components affected by bug:

### What is happening?

It looks like the Dash Bootstrap Components module was recently changed to not include the `Element` atttribute. When trying to use this attribute, I am receiving the error `AttributeError: module 'dash_html_components' has no attribute 'Element'`

### What should be happening?

Using `dash_bootstrap_components.Element` used to work

### Code

```python
import dash_html_components as html
def TitleBar(title: str, subtitle: str) -> html.Element:
```

**Comment by AnnMarieW** [comment]
Hi @jbatch01 

I think this might be an issue with Dash.  Since `<element>` is obsolete, `html.Element` may have been dropped in V2.0.0
see: https://dash.plotly.com/dash-html-components/element

![image](https://user-images.githubusercontent.com/72614349/132114927-ba654e67-7f95-48b4-9f93-9d2b73309ece.png)

**Comment by jbatch01** [comment]
Thanks for the information @AnnMarieW
