### ISSUE TITLE
`Select.options.value` support for types like boolean and int

### ISSUE THREAD

**Issue by aiqc** [facultyai/dash-bootstrap-components#825]
It would be nice to have Select support for boolean `value`'s.

It's super confusing when debugging that booleans actually get passed through as 'true' and 'false' so it looks like it working, but if you check the type it's just a string.

https://dash-bootstrap-components.opensource.faculty.ai/docs/components/input/

```python
opts = [
    dict(label="False",value=False),
    dict(label="True",value=True),
]

# printing their type and value in a callback
<class 'str'>
false

<class 'str'>
true
```

It feels silly to have to parse it:
```python
if (value=='False'):
    value = False
elif (value=='True'):
    value = True
```

And you can wind up with bad situations like

```python
>>> if ('false'): print("yolo")

"yolo"
```

**Comment by tcbegley** [comment]
Hey @aiqc 

The reason for this is because `Select` is just wrapping a [HTML select](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) element, which requires that the values are strings. When you pass a boolean or an integer, Dash converts it to a string for you rather than raise an error, but that means you end up getting a string back in callbacks.

It would be possible to have Dash not do this conversion, and then convert to strings inside the component, but this would create two problems:
- It would be hard to know / check if a value like `"true"` should be converted back to boolean when it's used to trigger a callback. In some cases it should be, but sometimes the user might be passing the actual string.
- We would have to do something clever to allow the component to understand that `10` and `"10"` are different values (they would be the same after converting to strings)

**Comment by aiqc** [comment]
@tcbegley

> raise an error

Agreed, that the desired behavior should be either:

- Raise an error if it's not a string rather than just pushing through `str(value)`.
- Or pass the original type through as an argument until the final step where it attempts to reapply to the str.

I guess this is why pickle/dill is a thing

**Comment by aiqc** [comment]
Closing as a Dash issue

**Comment by DeKhaos** [comment]
Took a while to find the cause to my problem, this is exactly the problem I'm having. Callback just keep convert int `value` of `dbc.Select` to str. But initially when the callback is called the first time, it actually returns int type, which is kind of confusing to handle.

Is there no other ways but for developers to handle if the input was a boolean|int|str variable inside the callback?

```
from dash import Dash,html
from dash.dependencies import Input, Output
import dash_bootstrap_components as dbc


app = Dash(__name__,
           external_stylesheets=[dbc.themes.CYBORG,
                                 dbc.icons.BOOTSTRAP],)

app.layout = html.Div([
    dbc.Select(options=[
        {'label':'option1','value':1},
        {'label':'option2','value':2},
        {'label':'option3','value':3}
        ],
        value=1,
        id='select_1'),
    dbc.Label("Output type:"),
    html.Div(id='output')
])

@app.callback(
    Output('output','children'),
    Input('select_1','value')
    )
def testing(value):
    return str(type(value))

if __name__ == '__main__':
    app.run(debug=True)
```

Environment: `dash 2.7.0`, `dash_bootstrap_components 1.2.1`
