### ISSUE TITLE
Make `step` validation optional

### ISSUE THREAD

**Issue by aiqc** [facultyai/dash-bootstrap-components#826]
I want to use `step` because it gives my up/down buttons something to use. However, I don't want it to validate that manually input number are valid steps.

Here the `step=0.1` and 0.15 is invalid

![image](https://user-images.githubusercontent.com/74990642/158460254-301dcf4b-6eed-46cb-b5c7-6dc327bd2005.png)

**Comment by tcbegley** [comment]
Hey @aiqc 

Thanks for raising. There's two aspects to this:
- Preventing the red box from appearing indicating input is invalid
- Making the callback fire if a value is entered that isn't a multiple of the step

The former is relatively easy. It's actually dash-core-components that's to blame here for adding the red box (some css is bundled with Dash apps for `dcc.Input`). You can override this behaviour with some custom CSS.

```css
input:invalid {
  outline: none !important;
}
```

The second point is more complicated, because we're trying above all to be consistent with the behaviour of `dcc.Input`. That means that we should only trigger callbacks when a valid input is supplied.

If you want to allow arbitrary numeric input, but still want the increment / decrement arrows, I suggest implementing this yourself with a callback and a `dbc.InputGroup` as follows

```python
import dash_bootstrap_components as dbc
from dash import Dash, Input, Output, State
from dash import callback_context as ctx
from dash import html, no_update

app = Dash(external_stylesheets=[dbc.themes.DARKLY, dbc.icons.FONT_AWESOME])

app.layout = dbc.Container(
    [
        dbc.InputGroup(
            [
                dbc.Input(id="input", type="number", value=0, min=0, max=10),
                dbc.Button(html.I(className="fas fa-angle-down"), id="down"),
                dbc.Button(html.I(className="fas fa-angle-up"), id="up"),
            ]
        ),
        html.Div(id="output"),
    ],
    className="p-5",
)


@app.callback(
    Output("input", "value"),
    Input("down", "n_clicks"),
    Input("up", "n_clicks"),
    State("input", "value"),
)
def change_value(n_down, n_up, value):
    if not ctx.triggered:
        return no_update
    else:
        button_id = ctx.triggered[0]["prop_id"].split(".")[0]

    if button_id == "up":
        value += 0.1
    else:
        value -= 0.1

    return round(value, 1)


@app.callback(Output("output", "children"), Input("input", "value"))
def return_value(value):
    return value


if __name__ == "__main__":
    app.run_server(debug=True)
```

You can hide the browser increment / decrement buttons with some CSS

```css
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type="number"] {
  -moz-appearance: textfield;
}
```

<img width="302" alt="image" src="https://user-images.githubusercontent.com/15220906/158756062-ae3fa491-2d57-4ff1-bbbc-9448042c3f19.png">

**Comment by tcbegley** [comment]
Closing this as I don't believe we can change anything without deviating from the behaviour of dash-core-components.

Feel free to reopen if you disagree or if something isn't clear.
