### ISSUE TITLE
Clarification on submitting forms

### ISSUE THREAD

**Issue by VictorLFandino** [facultyai/dash-bootstrap-components#843]
Hello

after having a look at the [documentation](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/form/), it is not clear for me if a form can be submitted from a callback or this is only possible specifying the `action` and `method` arguments and setting the `prevent_default_on_submit` argument to False, so when clicking on the submit button the action is performed. I need the submission to be done in a callback for further processing, but I don't know how the `action` and `method` arguments play there.

Thank you very much indeed

**Comment by VictorLFandino** [comment]
Hello

Thank you for your answer @tcbegley. The point is that I would like to leverage the action and method keywords in order to do a POST from the callback and get the result back. Is this possible?

Thanks

**Comment by tcbegley** [comment]
Hey @VictorLFandino 

I don't think it is possible, because when you use action + method to submit a post request, you will navigate away from the app which will interrupt execution of the callback.

What's the use case? Usually the default submit behaviour of the form action is just used to send the form data to a particular server somewhere. The callback is already sending data to the Flask server running your app, so I'm not sure I understand why you would want to submit it twice via two different methods.

If you need to forward data on to a second backend service, I would suggest processing the form information in your callback, and then issuing a post request from the callback body before returning.

**Comment by VictorLFandino** [comment]
Hello @tcbegley 

I understand that processing the form in the callback is the best option.

Thank you very much
