### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by CatChenal** [facultyai/dash-bootstrap-components#880]
In README.md, the link to the licence file:
```
[Apache 2.0 license](./LICENSE.txt)
```
yields a 404 error:
```
The 'facultyai/dash-bootstrap-components' repository doesn't contain the 'LICENSE.txt' path in 'main'.
```
because the file `LICENSE` does not have an extension.

PS: The bug option for this 'typo' was the most adequate viz the Bug vs Feature choice; perhaps add template files for "Other" in `.github/ISSUE_TEMPLATE/`?

**Comment by tcbegley** [comment]
Thanks! Fixed in #883 

> PS: The bug option for this 'typo' was the most adequate viz the Bug vs Feature choice; perhaps add template files for "Other" in .github/ISSUE_TEMPLATE/?

It's not that prominent in the UI, but you do have the option of opening a blank issue, or you can just delete the pre-populated content. All that the selection does is add some boilerplate text.

<img width="1181" alt="Screenshot 2022-07-31 at 10 12 59" src="https://user-images.githubusercontent.com/15220906/182019405-ea001245-9149-491c-8cb1-07e42b616898.png">
