### ISSUE TITLE
The dbc.Input component does not work properly with dbc.Form and "required = True"

### ISSUE THREAD

**Issue by james-duvall** [facultyai/dash-bootstrap-components#889]
First of all, thank you so much for creating dash_bootstrap_components. I love Dash, but it was previously so difficult to get the components to look reasonable out of the box.

Here is a minor styling issue that I am having with the Input component:

- dash version: `#2.5.1`
- dash-bootstrap-components version: `#1.2.1`
- components affected by bug: `dash_bootstrap_components.Input`

### What is happening?

When the `Input` component with `required = True` is used in a `Form`, the `Input` gets styled with a red border as soon as the page loads. The red border looks similar to the `invalid = True` style, but not the same. This is different from the way that `Select` and `Textarea` components work. The "Please fill out this field" popup works correctly, but the border styling is incorrect.

### What should be happening?

The `Input` component should display in the normal style. The validation styling should only be triggered if a validation criteria is not met and the user attempts to submit the form.

I searched the issue tracker and found #551, which was when the required attribute was added. I ran the example code there and it does not seem to work correctly. Maybe this issue was introduced upstream after #552 was implemented. I didn't find any other related issues. 

### Minimal working example

```python
# -*- coding: utf-8 -*-
"""
Minimal example of Input component validation issue
"""

from dash import Dash, html
import dash_bootstrap_components as dbc

app = Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])
app.layout = dbc.Container(
    dbc.Form(
        [
            html.H3("Example Form showing Input component validation issue"),
            html.Div(
                [
                    dbc.Label("This Select control looks good"),
                    dbc.Select(
                        placeholder="Select an option",
                        options=[
                            {"value": 0, "label": "Option 0"},
                            {"value": 1, "label": "Option 1"},
                        ],
                        required = True,
                    ),
                ],
            ),
            html.Div(
                [
                    dbc.Label("This Textarea control looks good too"),
                    dbc.Textarea(
                        placeholder="Enter some text",
                        required=True,
                    ),
                ],
            ),
            html.Div(
                [
                    dbc.Label("This Input control shouldn't be red until after attempting submit"),
                    dbc.Input(
                        placeholder="Enter some text",
                        type="text",
                        required=True,
                        invalid = True
                    ),
                ],
            ),
            dbc.Button("Submit"),
        ],
    )
)

app.run_server(debug=True)
```

### Error messages

There are no errors, but here is a picture of the incorrect styling
![image](https://user-images.githubusercontent.com/20895143/186738266-e3cc16a4-3086-4c57-a9e4-73973d810571.png)

**Comment by tcbegley** [comment]
Hey @james-duvall 

Thanks for reporting this and the kind words.

This problem arises because Dash actually bundles a small amount of CSS in every app. See [here](https://github.com/plotly/dash/blob/5c2f05e7a557716f0bfe2633e394fca1c6342ea9/components/dash-core-components/src/components/css/input.css#L1-L3) specifically where it adds a red outline to any invalid input. The reason this causes an issue is that a required input that has no value is actually in an invalid state, it's just that the application logic should only feed that back to the user after there's been an attempt to submit. Unfortunately the bundled CSS is a bit of a blunt instrument that is intended for styling dash-core-components but impacts any input elements created by other libraries.

I'd encourage you to raise an issue over at [plotly/dash](https://github.com/plotly/dash) to see if they are willing to fix this upstream by using a more specific CSS selector. In the meantime the best thing you can do is create some custom CSS, e.g. in your app's `assets/` folder that undoes this. E.g.

```css
input:invalid {
  outline: none;
}
```

Note that in your code snippet you have `invalid=True` so you will still see red when you make this change, but you'll notice it looks different and disappears when you remove that line.

Hope this helps!

**Comment by james-duvall** [comment]
@tcbegley,

Thanks for the quick response and the CSS workaround. It works for me.

The `invalid = True` line in my code snippet is a mistake. I was playing around with a few different things and I didn't mean to include that with my example.

I will submit the issue with the plotly/dash team.
