### ISSUE TITLE
Question for `dbc.Table.from_dataframe` definition

### ISSUE THREAD

**Issue by stdedos** [facultyai/dash-bootstrap-components#925]
Hello there!

I am wondering, why is `dbc.Table.from_dataframe` declared like this?

https://github.com/facultyai/dash-bootstrap-components/blob/fb8c3c72c50f343f4d0c74164ed61f2c5afc5b2b/dash_bootstrap_components/__init__.py#L37-L39

It seems to cause some issues on my `pylint` checking:
```
sa.py:116:11: E1101: Class 'Table' has no 'from_dataframe' member (no-member)
```

Is there ... some issue declaring it "normally"? Like
```py
    @classmethod
    def from_dataframe(...): ...
```

Maybe that would help `pylint` in identifying it properly.

PS: Not a `pylint` connoisseur, YMMV since idk if my configuration "makes sense" or not

**Comment by tcbegley** [comment]
Hey @stdedos 

Good question. It's because `Table` is defined and generated from [this JavaScript file](https://github.com/facultyai/dash-bootstrap-components/blob/main/src/components/table/Table.js) (this is how Dash components are generated in general). Modifying / intercepting this component generation pipeline is too complicated, so we simply define `from_dataframe` inside `__init__.py`. You'll notice that nowhere in the source code do we define `class Table`.

That's interesting that this causes pylint issues, I hadn't seen this before. Perhaps it could be resolved by dropping the `sys.modules[__name__]` and simply doing `Table.from_dataframe = ...`. That might help pylint realise that we're modifying the same `Table` class that you end up using.

**Comment by stdedos** [comment]
I asked the same question un-off on pylint too (https://discord.com/channels/825463413634891776/825463413634891779/1060572384609980446)

**Comment by tcbegley** [comment]
That link doesn't appear to be working for me, but let me know if you get any interesting answers. When I get a moment I'll try implementing the change I mentioned above and see if it resolves the issue.

**Comment by Pierre-Sassoulas** [comment]
You can use the 'generated-members' option to tell pylint about this kind of thing. (Check the documentation for no-member for details)

**Comment by stdedos** [comment]
Oh - so, "library cannot do anything about that"?

It's so sad to have to add exceptions locally 😢

**Comment by tcbegley** [comment]
Thanks for the pointers and the invite @Pierre-Sassoulas! Good to know about `generated-members`.

@stdedos I just made a pre-release that fixes this issue on our side. It's working locally for me without any additional configuration of Pylint. Please try it out and let me know if you still have issues. All being well this will make it into a full release in the near future.

```
pip install dash-bootstrap-components==1.3.1rc1
```

**Comment by stdedos** [comment]
> @stdedos I just made a pre-release that fixes this issue on our side. It's working locally for me without any additional configuration of Pylint. Please try it out and let me know if you still have issues. All being well this will make it into a full release in the near future.
> 
> ```
> pip install dash-bootstrap-components==1.3.1rc1
> ```

That's weird that "it fixes it from your side, since I thought that

> That's interesting that this causes pylint issues, I hadn't seen this before.

😅 

You didn't have to make a full pre-release to test it (I could've just `git+https`), but it seems it's the correct way forward! So now `pylint` does not complain anymore 🥳 

You can go ahead and release this as a proper minor version, I guess - if you feel that's safe for you to do so.

Thank you both @tcbegley @Pierre-Sassoulas for chiming in 😊

**Comment by tcbegley** [comment]
> That's weird that "it fixes it from your side", since I thought that [you hadn't seen this before]

Yes, that's more to do with the fact that I tend to use flake8 for linting rather than Pylint which is less comprehensive in the checks that it does. So I hadn't seen the error because I was using a different tool, not because the error didn't occur on my system.

> You can go ahead and release this as a proper minor version, I guess

That's the plan, just a couple of other things I want to include in that too, but will probably make the release in the next couple of days.
