### ISSUE TITLE
assets/style.css has no effect on rendered output

### ISSUE THREAD

**Issue by jacopo-chevallard** [facultyai/dash-bootstrap-components#934]
Hi all, first, congrats for the beautiful library !!! 👏👏👏👏

I looked for the answer to the following question, but I couldn't find it, nor I could find a workaround: I'm using one of your themes (BOOTSTRAP) to be able to use dbc.Col and dbc.Row (among other things), but I would also like to use my custom style.css file (located in assets/style.css). 

It seems, however, that the style.css file is not taken into account (in terms of text and background colors, for instance) when calling
```python
from dash import Dash
app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])
```
while it is taken into account when I just use
```python
from dash import Dash
app = Dash()
```
Any hint would be very much appreciated !

**Comment by AnnMarieW** [comment]
Hi @jacopo-chevallard 

Glad you like Dash Bootstrap Components!

Since this is more of a "how-to" question rather than an issue with this library, it would be better to ask your question on the [Dash Community Forum](https://community.plotly.com/). 

 I can answer you  over there -- and when you create the post, it's helpful to include a minimal example that shows the issues.  More info on how to do that here:  [How to get your questions answered on the forum](https://community.plotly.com/t/how-to-get-your-questions-answered-on-the-plotly-forum/40551).    You may also find the [Dash Bootstrap Theme Explorer](https://hellodash.pythonanywhere.com/) helpful - it has lots of information on how to style your app.
