### ISSUE TITLE
Is there a way to use an icon as a label in a dbc.Tab element?

### ISSUE THREAD

**Issue by araichev** [facultyai/dash-bootstrap-components#959]
I naively tried  `dbc.Tab(<stuff>, label=html.I(className="bi bi-info"))` and that failed.

**Comment by tcbegley** [comment]
Hi @araichev 

Unfortunately this isn't supported at the moment, but you can try [this workaround](https://github.com/facultyai/dash-bootstrap-components/issues/478).

I will look into whether changes in dash-renderer since that issue was opened allow us to do things in a better way, but afaik for the tab component specifically things are a little tricky.

**Comment by araichev** [comment]
Thanks for your response @tcbegley and sorry for not seeing that closed duplicate issue.
I might try the workaround.
