### ISSUE TITLE
Keyword argument for value OR placeholder

### ISSUE THREAD

**Issue by ThomDietrich** [facultyai/dash-bootstrap-components#981]
Hey friends,

**Context:** Many dbc components (specifically `dbc.Input` in my case) offer the ability to set a placeholder. In my use case I present a default value via the placeholder attribute while the user can add their custom value as an input.

In further processing via a callback function I would like to take into account the custom value if provided, or the placeholder otherwise.

```python
@callback(
    Output("out", "value"),
    Input("in", "value"),
    Input("in", "placeholder"),
)
def show_result(in_value, in_placeholder):
    return in_value if in_value else in_placeholder
```

**Feature Request:** Please consider the addition of a property which holds the combined content. The example from above would look like this:

```python
@callback(
    Output("out", "value"),
    Input("in", "content"),
)
def show_result(in_content):
    return in_content
```

Thank you!

**Comment by tcbegley** [comment]
Hi @ThomDietrich 

Thanks for raising this. After some consideration I'm afraid I've concluded this is not something we'll implement. I am worried we could cause confusion by making multiple props holding variants of the same data, and we'd be diverging from behaviour of the corresponding HTML elements making the behaviour of the components less predictable. On top of that I think the benefit is fairly marginal, your solution is a one-liner after all.

BTW since the user has no mechanism to change the placeholder you can either pass it as `State` to the callback, or you could even just define a global variable that you use to set the placeholder + use in the callback.

**Comment by ThomDietrich** [comment]
Thanks for consideration and thanks for the thoughtful response. Cheers :)
